routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// front end routes
//Route::get('/', 'FrontController@index');

Route::get('/',function(){
    return redirect()->to('/admin');
});

Auth::routes();

Route::get('/run', 'MainController@index');
Route::get('/home', 'HomeController@index');

// admin routes
Route::group(['middleware'=>'auth' , 'prefix' => 'admin'],function(){
    Route::get('/','HomeController@index');
    Route::resource('city', 'CityController');
    Route::resource('region', 'RegionController');
    Route::resource('category', 'CategoryController');
    Route::resource('offer', 'OfferController');
    Route::get('restaurant/{id}/activate', 'RestaurantController@activate');
    Route::get('restaurant/{id}/de-activate', 'RestaurantController@deActivate');
    Route::resource('restaurant','RestaurantController');
    Route::resource('{restaurant}/item', 'ItemController');
    Route::resource('order','OrderController');
    Route::resource('transaction','TransactionController');
//    Route::resource('page','PageController');
    Route::resource('payment-method','PaymentMethodController');
    Route::resource('delivery-method','DeliveryMethodController');
    Route::resource('contact','ContactController');
    Route::resource('client','ClientController');

    Route::get('settings','SettingsController@view');
    Route::post('settings','SettingsController@update');
    
    // user reset
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');
//    Route::resource('user','UserController');
//    Route::resource('role','RoleController');
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaction;
use Response;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $transactions = Transaction::where(function($q) use($request) {
            if ($request->has('restaurant_id')){
                $q->where('restaurant_id',$request->restaurant_id);
            }
        })->latest()->paginate(20);
        return view('admin.transactions.index',compact('transactions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Transaction $model
     * @return \Illuminate\Http\Response
     */
    public function create(Transaction $model)
    {
        return view('admin.transactions.create',compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'restaurant_id' => 'required',
            'amount' => 'required|numeric'
        ]);

        $transaction = new Transaction;
        $transaction->restaurant_id = $request->restaurant_id;
        $transaction->amount = $request->amount;
        $transaction->note = $request->note;
        $transaction->save();

        flash()->success('تم إضافة العملية المالية بنجاح');
        return redirect('admin/transaction');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Transaction::findOrFail($id);
        return view('admin.transactions.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'restaurant_id' => 'required',
            'amount' => 'required|numeric'
        ]);

        $transaction = Transaction::findOrFail($id);
        $transaction->restaurant_id = $request->restaurant_id;
        $transaction->amount = $request->amount;
        $transaction->note = $request->note;
        $transaction->save();

        flash()->success('تم تعديل العملية المالية بنجاح.');
        return redirect('admin/transaction');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaction = Transaction::findOrFail($id);
        $transaction->delete();
        $data = [
            'status' => 1,
            'msg' => 'تم الحذف بنجاح',
            'id' => $id
        ];
        return response()->json($data, 200);
    }
}

resources/views/admin/transactions/create.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'العمليات المالية',
                                'page_description'  => 'إضافة العمليات المالية'
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'TransactionController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST',
                            'files'=>true
                            ])!!}

    <div class="box-body">
        @include('admin.transactions.form',$model)
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/transactions/edit.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'العمليات المالية',
                                'page_description'  => 'تعديل العمليات المالية'
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>['TransactionController@update',$model->id],
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT',
                            'files'=>true
                            ])!!}

    <div class="box-body">

        @include('admin.transactions.form',compact('model'))

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ التعديل</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/transactions/form.blade.php
@include('admin.layouts.partials.validation-errors')
@include('flash::message')

@inject('restaurant','App\Models\Restaurant')

{!! \App\Ibnfarouk\MyClasses\Field::select('restaurant_id','المطعم  ',$restaurant->get()->pluck('restaurant_details','id')->toArray()) !!}
{!! \App\Ibnfarouk\MyClasses\Field::number('amount' , 'المبلغ') !!}
{!! Field::text('note','بيان العملية') !!}

resources/views/admin/transactions/index.blade.php
@extends('admin.layouts.main',[
								'page_header'		=> 'العمليات المالية',
								'page_description'	=> 'عرض العمليات'
								])
@inject('restaurant','App\Models\Restaurant')

@section('content')
    <div class="box box-primary">
        <div class="box-header">
            <div class="pull-right">
                <a href="{{url('admin/transaction/create')}}" class="btn btn-primary">
                    <i class="fa fa-plus"></i>  إضافة عملية مالية
                </a>
            </div>
        </div>
        <div class="box-body">
            @include('flash::message')
            <div class="filter">
                {!! Form::open([
                            'action'=>'TransactionController@index',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'GET',
                            ])!!}
                <div class="row">
                    <div class="col-md-3">
                        {!! Field::select('restaurant_id','',$restaurant->get()->pluck('restaurant_details','id')->toArray()) !!}
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="">&nbsp;</label>
                            <button type="submit" class="btn btn-flat bg-navy btn-block"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
            @if(!empty($transactions))
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <th>#</th>
                        <th>اسم المطعم</th>
                        <th>المبلغ</th>
                        <th>بيان العملية</th>
                        <th class="text-center">تعديل</th>
                        <th class="text-center">حذف</th>
                        </thead>
                        <tbody>
                        @php $count = 1; @endphp
                        @foreach($transactions as $transaction)
                            <tr id="removable{{$transaction->id}}">
                                <td>{{$count}}</td>
                                <td>{{(count($transaction->restaurant)) ? $transaction->restaurant->name : ''}}</td>
                                <td>{{$transaction->amount}}</td>
                                <td>{{$transaction->note}}</td>
                                <td class="text-center">
                                    <a href="transaction/{{$transaction->id}}/edit" class="btn btn-xs btn-success">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <button id="{{$transaction->id}}" data-token="{{ csrf_token() }}"
                                            data-route="{{URL::route('transaction.destroy',$transaction->id)}}"
                                            type="button" class="destroy btn btn-danger btn-xs"><i
                                                class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                            @php $count ++; @endphp
                        @endforeach
                        </tbody>
                    </table>
                </div>

                <div class="text-center">
                    {!! $transactions->appends([
                    'restaurant_id' => \Request::input('restaurant_id'),
                ])->render() !!}
                </div>
            @endif
        </div>
    </div>
@stop