routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// front end routes
//Route::get('/', 'FrontController@index');

Route::get('/',function(){
    return redirect()->to('/admin');
});

Auth::routes();

Route::get('/run', 'MainController@index');
Route::get('/home', 'HomeController@index');

// admin routes
Route::group(['middleware'=>'auth' , 'prefix' => 'admin'],function(){
    Route::get('/','HomeController@index');
    Route::resource('city', 'CityController');
    Route::resource('region', 'RegionController');
    Route::resource('category', 'CategoryController');
    Route::resource('offer', 'OfferController');
    Route::get('restaurant/{id}/activate', 'RestaurantController@activate');
    Route::get('restaurant/{id}/de-activate', 'RestaurantController@deActivate');
    Route::resource('restaurant','RestaurantController');
    Route::resource('{restaurant}/item', 'ItemController');
    Route::resource('order','OrderController');
    Route::resource('transaction','TransactionController');
//    Route::resource('page','PageController');
    Route::resource('payment-method','PaymentMethodController');
    Route::resource('delivery-method','DeliveryMethodController');
    Route::resource('contact','ContactController');
    Route::resource('client','ClientController');

    Route::get('settings','SettingsController@view');
    Route::post('settings','SettingsController@update');
    
    // user reset
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');
//    Route::resource('user','UserController');
//    Route::resource('role','RoleController');
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class Client extends Authenticatable {

	protected $table = 'clients';
	public $timestamps = true;
	protected $fillable = array('name', 'email', 'phone', 'address', 'password', 'region_id', 'api_token', 'code', 'profile_image');
	protected $appends = ['profile_path'];
	public function orders() {
		return $this->hasMany('App\Models\Order');
	}

	public function cart() {
		return $this->belongsToMany('App\Models\Item', 'carts')->withPivot('price', 'quantity', 'note', 'id');
	}

	public function region() {
		return $this->belongsTo('App\Models\Region');
	}

	public function tokens() {
		return $this->morphMany('App\Models\Token', 'accountable');
	}

	public function notifications() {
		return $this->morphMany('App\Models\Notification', 'notifiable');
	}

	function getProfilePathAttribute() {
		return asset($this->profile_image);
	}

	public static function boot() {
		parent::boot();
		static::deleted(function ($model) {
			if (file_exists($model->profile_image)) {
				unlink($model->profile_image);
			}

		});
	}

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password', 'api_token', 'code',
	];

}

app/Http/Controllers/Api/Client/AuthController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Models\Client;
use App\Models\Token;
use Hash;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Validation\Rule;
use Mail;

class AuthController extends Controller
{
    public function register(Request $request)
    {
        $validation = validator()->make($request->all(), [
            'name'      => 'required',
            'phone'     => 'required',
            'region_id' => 'required',
            'address'   => 'required',
            'email'     => 'required|unique:clients,email',
            'password'  => 'required|confirmed',
            'profile_image'  => 'required|image|mimes:png,jpeg',
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        $userToken = str_random(60);
        $request->merge(array('api_token' => $userToken));
        $request->merge(array('password' => bcrypt($request->password)));
        $user = Client::create($request->all());
        if ($request->hasFile('profile_image')) {

            $path = public_path();
            $destinationPath = $path . '/uploads/clients/'; // upload path
            $photo = $request->file('profile_image');
            $extension = $photo->getClientOriginalExtension(); // getting image extension
            $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
            $photo->move($destinationPath, $name); // uploading file to given path
            $user->profile_image = 'uploads/clients/' . $name;
        }

        $user->save();
        if ($user) {
            $data = [
                'api_token' => $userToken,
                'client'      => $user->load('region')
            ];

            return responseJson(1, 'تم التسجيل بنجاح', $data);
        } else {
            return responseJson(0, 'حدث خطأ ، حاول مرة أخرى');
        }
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function profile(Request $request)
    {
        //dd($request->user()->id);
        $validation = validator()->make($request->all(), [
            'password'      => 'confirmed',
            Rule::unique('users')->ignore($request->user()->id),
            'profile_image' => 'image|mimes:png,jpeg',
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        if ($request->has('name')) {
            $request->user()->update($request->only('name'));
        }
        if ($request->has('email')) {
            $request->user()->update($request->only('email'));
        }
        if ($request->has('password')) {
            $request->merge(array('password' => bcrypt($request->password)));
            $request->user()->update($request->only('password'));
        }

        if ($request->has('phone')) {
            $request->user()->update($request->only('phone'));
        }

        if ($request->has('region_id')) {
            $request->user()->update($request->only('region_id'));
        }

        if ($request->has('address')) {
            $request->user()->update($request->only('address'));
        }

        $loginUser = $request->user();
        $loginUser->update($request->except('profile_image'));
        if ($request->hasFile('profile_image')) {
                if (file_exists($loginUser->profile_image))
                    unlink($loginUser->profile_image);

                $path = public_path();
                $destinationPath = $path . '/uploads/clients/'; // upload path
                $photo = $request->file('profile_image');
                $extension = $photo->getClientOriginalExtension(); // getting image extension
                $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
                $photo->move($destinationPath, $name); // uploading file to given path
                $loginUser->profile_image = 'uploads/clients/' . $name;
            }
            $loginUser->save();

        $data = [
            'client' => $request->user()->load('region')
        ];
        return responseJson(1, 'تم تحديث البيانات', $data);
    }


    /**
     * @param Request $request
     * @return mixed
     */
    public function login(Request $request)
    {
        $validation = validator()->make($request->all(), [
            'email'    => 'required',
            'password' => 'required'
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        $user = Client::where('email', $request->input('email'))->first();
        if ($user) {
            if (Hash::check($request->password, $user->password)) {
                // check if not activated
                $data = [
                    'api_token' => $user->api_token,
                    'client'      => $user->load('region'),
                ];
                return responseJson(1, 'تم تسجيل الدخول', $data);
            } else {
                return responseJson(0, 'بيانات الدخول غير صحيحة');
            }
        } else {
            return responseJson(0, 'بيانات الدخول غير صحيحة');
        }
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function reset(Request $request)
    {
        $validation = validator()->make($request->all(), [
            'email' => 'required'
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        $user = Client::where('email', $request->email)->first();
        if ($user) {
            $code = rand(111111, 999999);
            $update = $user->update(['code' => $code]);
            if ($update) {
                // send email
                Mail::send('emails.reset', ['code' => $code], function ($mail) use ($user) {
                    $mail->from('no-reply@ipda3.com', 'تطبيق أكلات');

                    $mail->to($user->email, $user->name)->subject('إعادة تعيين كلمة المرور');
                });

                return responseJson(1, 'برجاء فحص بريدك الالكتروني');
            } else {
                return responseJson(0, 'حدث خطأ ، حاول مرة أخرى');
            }
        } else {
            return responseJson(0, 'لا يوجد أي حساب مرتبط بهذا البريد الالكتروني');
        }
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function password(Request $request)
    {
        $validation = validator()->make($request->all(), [
            'code'     => 'required',
            'password' => 'confirmed'
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        $user = Client::where('code', $request->code)->where('code', '!=', 0)->first();

        if ($user) {
            $update = $user->update(['password' => bcrypt($request->password), 'code' => null]);
            if ($update) {
                return responseJson(1, 'تم تغيير كلمة المرور بنجاح');
            } else {
                return responseJson(0, 'حدث خطأ ، حاول مرة أخرى');
            }
        } else {
            return responseJson(0, 'هذا الكود غير صالح');
        }
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function registerToken(Request $request)
    {
        $validation = validator()->make($request->all(), [
            'type'  => 'required|in:android,ios',
            'token' => 'required',
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        Token::where('token', $request->token)->delete();

        $request->user()->tokens()->create($request->all());
        return responseJson(1, 'تم التسجيل بنجاح');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function removeToken(Request $request)
    {
        $validation = validator()->make($request->all(), [
            'token' => 'required',
        ]);

        if ($validation->fails()) {
            $data = $validation->errors();
            return responseJson(0, $validation->errors()->first(), $data);
        }

        Token::where('token', $request->token)->delete();
        return responseJson(1, 'تم الحذف بنجاح بنجاح');
    }
}

app/Http/Controllers/ClientController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Models\Client;
use Response;


class ClientController extends Controller {

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $clients = Client::with('region')->paginate(20);
    return view('admin.clients.index',compact('clients'));
  }

  /**
   * Show the form for creating a new resource.1
   *
   * @return Response
   */
  public function create()
  {
    $model = new Client;
    return view('admin.clients.create',compact('model'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $this->validate($request,[
          'title' => 'required'
      ]);
      $client = Client::create($request->all());

      flash()->success('تمت الإضافة بنجاح');
      return redirect('admin/client');


  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      $model = Client::findOrFail($id);
      return view('admin.clients.edit',compact('model'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id , Request $request)
  {
      $this->validate($request,[
          'title' => 'required'
      ]);
      $client = Client::findOrFail($id);
      $client->update($request->all());

      flash()->success('تم تعديل بيانات العرض بنجاح');
      return redirect('admin/client/'.$id.'/edit');
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
      $client = Client::findOrFail($id);
      $client->delete();
      $data = [
          'status' => 1,
          'msg' => 'تم الحذف بنجاح',
          'id' => $id
      ];
      return Response::json($data, 200);
  }
  
}

?>

resources/views/admin/clients/create.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'أصناف الطعام',
                                'page_description'  => 'صنف جديد'
                                ])
@section('content')
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-cutlery"></i> {{$restaurant->name}}</a></li>
    </ol>
    <!-- general form elements -->
    <div class="box box-primary">
        <!-- form start -->
        {!! Form::model($model,[
                                'action'=>['ItemController@store',$restaurant->id],
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'POST',
                                'files' => true
                                ])!!}
        <div class="box-body">
            @include('admin.items.form')
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">حفظ</button>
            </div>
        </div>
        {!! Form::close()!!}
    </div><!-- /.box -->
@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'أصناف الطعام',
                                'page_description'  => 'تعديل صنف'
                                ])
@section('content')
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-cutlery"></i> {{$restaurant->name}}</a></li>
    </ol>
    <!-- general form elements -->
    <div class="box box-primary">
        <!-- form start -->
        {!! Form::model($model,[
                                'url'=> 'admin/'.$restaurant->id.'/item/'.$model->id,
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'PUT',
                                'files' => true
                                ])!!}

        <div class="box-body">

            @include('admin.items.form')

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">حفظ</button>
            </div>

        </div>
        {!! Form::close()!!}

    </div><!-- /.box -->

@endsection

resources/views/admin/clients/form.blade.php
@include('admin.layouts.partials.validation-errors')
@include('flash::message')

@inject('section','App\Models\Section')
@php
$sections=[0 => '']+$section->where('restaurant_id',$restaurant->id)->pluck('name','id')->toArray();
@endphp

<div class="row">
    <div class="col-md-6">
        {!! Field::text('name' , 'اسم الصنف') !!}
    </div>
    <div class="col-md-6">
        {!! Field::text('name_en' , 'Item name') !!}
    </div>
    <div class="col-md-6">
        {!! Field::textarea('desc', 'وصف الصنف') !!}
    </div>
    <div class="col-md-6">
        {!! Field::textarea('desc_en', 'Item Description') !!}
    </div>
    <div class="clearfix"></div>
</div>

{!! Field::number('price' , 'السعر') !!}
{!! Field::select('section_id','أقسام القائمة',$sections) !!}
{!! Field::select('is_available','متاح',['1' => 'نعم', '0' => 'لا']) !!}
{!! Field::fileWithPreview('photo','صورة الصنف') !!}
@if($model->photo != '')
    <div class="col-md-3">
        <img src="{{asset($model->photo)}}" class="img-responsive" alt="">
    </div>
    <div class="clearfix"></div>
    <br>
@endif

resources/views/admin/clients/index.blade.php
@extends('admin.layouts.main',[
								'page_header'		=> 'العملاء',
								'page_description'	=> 'طالبي الطعام'
								])

@section('content')
    <div class="box box-primary">
        <div class="box-header">
        </div>
        <div class="box-body">
            @include('flash::message')
            @if(!empty($clients))
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <th>#</th>
                        <th>اسم العميل</th>
                        <th>الايميل</th>
                        <th>الهاتف</th>
                        <th>المدينة</th>
                        <th>العنوان</th>
                        <th class="text-center">حذف</th>
                        </thead>
                        <tbody>
                        @php $count = 1; @endphp
                        @foreach($clients as $client)
                            <tr id="removable{{$client->id}}">
                                <td>{{$count}}</td>
                                <td>{{$client->name}}</td>
                                <td>{{$client->email}}</td>
                                <td>{{$client->phone}}</td>
                                <td>
                                    @if(count($client->region))
                                        {{$client->region->name}}
                                        @if(count($client->region->city))
                                            {{$client->region->city->name}}
                                        @endif
                                    @endif
                                </td>
                                <td>{{$client->address}}</td>
                                <td class="text-center">
                                    <button id="{{$client->id}}" data-token="{{ csrf_token() }}"
                                            data-route="{{URL::route('client.destroy',$client->id)}}"
                                            type="button" class="destroy btn btn-danger btn-xs">
                                        <i class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                            @php $count ++; @endphp
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {!! $clients->render() !!}
            @endif
        </div>
    </div>
@stop