routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// front end routes
//Route::get('/', 'FrontController@index');

Route::get('/',function(){
    return redirect()->to('/admin');
});

Auth::routes();

Route::get('/run', 'MainController@index');
Route::get('/home', 'HomeController@index');

// admin routes
Route::group(['middleware'=>'auth' , 'prefix' => 'admin'],function(){
    Route::get('/','HomeController@index');
    Route::resource('city', 'CityController');
    Route::resource('region', 'RegionController');
    Route::resource('category', 'CategoryController');
    Route::resource('offer', 'OfferController');
    Route::get('restaurant/{id}/activate', 'RestaurantController@activate');
    Route::get('restaurant/{id}/de-activate', 'RestaurantController@deActivate');
    Route::resource('restaurant','RestaurantController');
    Route::resource('{restaurant}/item', 'ItemController');
    Route::resource('order','OrderController');
    Route::resource('transaction','TransactionController');
//    Route::resource('page','PageController');
    Route::resource('payment-method','PaymentMethodController');
    Route::resource('delivery-method','DeliveryMethodController');
    Route::resource('contact','ContactController');
    Route::resource('client','ClientController');

    Route::get('settings','SettingsController@view');
    Route::post('settings','SettingsController@update');
    
    // user reset
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');
//    Route::resource('user','UserController');
//    Route::resource('role','RoleController');
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model {

	protected $table = 'contacts';
	public $timestamps = true;
	protected $fillable = array('name', 'email', 'phone', 'content', 'type');
	protected $appends = ['type_text'];

    public function getTypeTextAttribute()
    {
        $types = [
            'complaint' => 'شكوى',
            'suggestion' => 'اقتراح',
            'inquiry' => 'استعلام',
        ];

        if (isset($types[$this->type])) {
            return $types[$this->type];
        }
        return "";
    }

}

app/Http/Controllers/ContactController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Models\Contact;
use Response;


class ContactController extends Controller {

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $contacts = Contact::latest()->paginate(20);
    return view('admin.contacts.index',compact('contacts'));
  }

  /**
   * Show the form for creating a new resource.1
   *
   * @return Response
   */
  public function create()
  {
    $model = new Contact;
    return view('admin.contacts.create',compact('model'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $this->validate($request,[
          'title' => 'required'
      ]);
      $contact = Contact::create($request->all());

      flash()->success('تم إضافة العرض بنجاح');
      return redirect('admin/contact');


  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      $model = Contact::findOrFail($id);
      return view('admin.contacts.edit',compact('model'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id , Request $request)
  {
      $this->validate($request,[
          'title' => 'required'
      ]);
      $contact = Contact::findOrFail($id);
      $contact->update($request->all());

      flash()->success('تم تعديل بيانات العرض بنجاح');
      return redirect('admin/contact/'.$id.'/edit');
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
      $contact = Contact::findOrFail($id);
      $contact->delete();
      $data = [
          'status' => 1,
          'msg' => 'تم الحذف بنجاح',
          'id' => $id
      ];
      return Response::json($data, 200);
  }
  
}

?>

resources/views/admin/contacts/create.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'العروض',
                                'page_description'  => 'عرض جديد'
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'OfferController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST',
                            'files'=>true
                            ])!!}

    <div class="box-body">

        @include('admin.offers.form',$model)

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/contacts/edit.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'العروض',
                                'page_description'  => 'تعديل عرض'
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>['OfferController@update',$model->id],
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT',
                            'files'=>true
                            ])!!}

    <div class="box-body">

        @include('admin.offers.form',compact('model'))

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/contacts/form.blade.php
@include('admin.layouts.partials.validation-errors')
@include('flash::message')
@inject('restaurant','App\Models\Restaurant')

@php
$restaurants = [ '' => 'اختر المطعم'] + $restaurant->pluck('name','id')->toArray();
@endphp
{!! \App\Ibnfarouk\MyClasses\Field::text('title' , 'العنوان') !!}
{!! \App\Ibnfarouk\MyClasses\Field::textarea('content','محتوى العرض') !!}
{!! Field::select('restaurant_id','اختر المطعم',$restaurants , 'اختر المطعم') !!}
<div class="row">
    <div class="col-md-6">
        {!! \App\Ibnfarouk\MyClasses\Field::date('date_from','بداية العرض') !!}
    </div>
    <div class="col-md-6">
        {!! \App\Ibnfarouk\MyClasses\Field::date('date_to','نهاية العرض') !!}
    </div>
</div>

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.main',[
								'page_header'		=> 'العروض',
								'page_description'	=> 'عرض العروض'
								])
@section('content')
    <div class="box box-primary">
        <div class="box-header">
            {{--<div class="pull-right">--}}
                {{--<a href="{{url('admin/contact/create')}}" class="btn btn-primary">--}}
                    {{--<i class="fa fa-plus"></i> عرض جديد--}}
                {{--</a>--}}
            {{--</div>--}}
        </div>
        <div class="box-body">
            @include('flash::message')
            @if(!empty($contacts))
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <th>#</th>
                        <th>الاسم</th>
                        <th>الهاتف</th>
                        <th>الايميل</th>
                        <th>الرسالة</th>
                        {{--<th class="text-center">تعديل</th>--}}
                        <th class="text-center">حذف</th>
                        </thead>
                        <tbody>
                        @php $count = 1; @endphp
                        @foreach($contacts as $contact)
                            <tr id="removable{{$contact->id}}">
                                <td>{{$count}}</td>
                                <td>{{$contact->name}}</td>
                                <td>{{$contact->phone}}</td>
                                <td>{{$contact->email}}</td>
                                <td>{{$contact->content}}</td>
                                {{--<td class="text-center"><a href="contact/{{$contact->id}}/edit"--}}
                                                           {{--class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a>--}}
                                {{--</td>--}}
                                <td class="text-center">
                                    <button id="{{$contact->id}}" data-token="{{ csrf_token() }}"
                                            data-route="{{URL::route('contact.destroy',$contact->id)}}"
                                            type="button" class="destroy btn btn-danger btn-xs"><i
                                                class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                            @php $count ++; @endphp
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {!! $contacts->render() !!}
            @endif
        </div>
    </div>
@stop