routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// front end routes
//Route::get('/', 'FrontController@index');

Route::get('/',function(){
    return redirect()->to('/admin');
});

Auth::routes();

Route::get('/run', 'MainController@index');
Route::get('/home', 'HomeController@index');

// admin routes
Route::group(['middleware'=>'auth' , 'prefix' => 'admin'],function(){
    Route::get('/','HomeController@index');
    Route::resource('city', 'CityController');
    Route::resource('region', 'RegionController');
    Route::resource('category', 'CategoryController');
    Route::resource('offer', 'OfferController');
    Route::get('restaurant/{id}/activate', 'RestaurantController@activate');
    Route::get('restaurant/{id}/de-activate', 'RestaurantController@deActivate');
    Route::resource('restaurant','RestaurantController');
    Route::resource('{restaurant}/item', 'ItemController');
    Route::resource('order','OrderController');
    Route::resource('transaction','TransactionController');
//    Route::resource('page','PageController');
    Route::resource('payment-method','PaymentMethodController');
    Route::resource('delivery-method','DeliveryMethodController');
    Route::resource('contact','ContactController');
    Route::resource('client','ClientController');

    Route::get('settings','SettingsController@view');
    Route::post('settings','SettingsController@update');
    
    // user reset
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');
//    Route::resource('user','UserController');
//    Route::resource('role','RoleController');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model {

	protected $table = 'categories';
	public $timestamps = true;
	protected $fillable = array('name');

	public function restaurants()
	{
		return $this->belongsToMany('App\Models\Restaurant');
	}

}

app/Http/Controllers/CategoryController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Models\Category;
use Response;


class CategoryController extends Controller {

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $categories = Category::paginate(20);
    return view('admin.categories.index',compact('categories'));
  }

  /**
   * Show the form for creating a new resource.1
   *
   * @return Response
   */
  public function create()
  {
    $model = new Category;
    return view('admin.categories.create',compact('model'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $this->validate($request,[
          'name' => 'required'
      ]);
      Category::create($request->all());
      flash()->success('تم إضافة القسم بنجاح');
      return redirect('admin/category');


  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      $model = Category::findOrFail($id);
      return view('admin.categories.edit',compact('model'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id , Request $request)
  {
      $this->validate($request,[
          'name' => 'required',
      ]);
      Category::findOrFail($id)->update($request->all());
      flash()->success('تم تعديل بينات القسم بنجاح');
      return redirect('admin/category');
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
      $category = Category::findOrFail($id);
      $count = $category->restaurants()->count();
      if ($count > 0)
      {
          $data = [
              'status' => 0,
              'msg' => 'لا يمكن مسح التصنيف ، يوجد مطاعم مسجلة به'
          ];
          return Response::json($data, 200);
      }
      $category->delete();
      $data = [
          'status' => 1,
          'msg' => 'تم الحذف بنجاح',
          'id' => $id
      ];
      return Response::json($data, 200);
  }
  
}

?>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'تصنيفات المطاعم',
                                'page_description'  => 'تصنيف جديد'
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'CategoryController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST'
                            ])!!}

    <div class="box-body">

        @include('admin.categories.form')

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.main',[
                                'page_header'       => 'تصنيفات المطاعم',
                                'page_description'  => 'تعديل تصنيف'
                                ])
@section('content')
        <!-- general form elements -->
<div class="box box-primary">
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>['CategoryController@update',$model->id],
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT'
                            ])!!}

    <div class="box-body">

        @include('admin.categories.form')

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>

    </div>
    {!! Form::close()!!}

</div><!-- /.box -->

@endsection

resources/views/admin/categories/form.blade.php
@include('admin.layouts.partials.validation-errors')
@include('flash::message')

{!! Field::text('name' , 'اسم التصنيف') !!}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.main',[
								'page_header'		=> 'التصنيفات',
								'page_description'	=> 'تصنيفات المطاعم'
								])
@section('content')
    <div class="box box-default">
        <div class="box-header">
            <div class="pull-right">
                <a href="{{url('admin/category/create')}}" class="btn btn-primary">
                    <i class="fa fa-plus"></i> تصنيف جديد
                </a>
            </div>
        </div>
        @if(!empty($categories))
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <th>#</th>
                <th>اسم القسم</th>
                <th class="text-center">تعديل</th>
                <th class="text-center">حذف</th>
                </thead>
                <tbody>
                    @php $count = 1; @endphp
                    @foreach($categories as $category)
                        <tr id="removable{{$category->id}}">
                            <td>{{$count}}</td>
                            <td>{{$category->name}}</td>
                            <td class="text-center"><a href="category/{{$category->id}}/edit" class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a></td>
                            <td class="text-center">
                                <button id="{{$category->id}}" data-token="{{ csrf_token() }}" data-route="{{URL::route('category.destroy',$category->id)}}"  type="button" class="destroy btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>
                            </td>
                        </tr>
                        @php $count ++; @endphp
                    @endforeach
                </tbody>
            </table>
        </div>
            {!! $categories->render() !!}
        @endif


    </div>
@stop